name: 🔄 Sync DB (Exact Copy from main → gh-pages)

on:
  push:
    branches:
      - main
    paths:
      - 'FrontEnd_Web/public/DB/**'  # only trigger when DB folder changes
  workflow_dispatch:  # 👈 allows manual trigger from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout main branch
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # 2️⃣ Clone gh-pages branch to temp folder
      - name: Clone gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git clone --branch gh-pages "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" gh-pages

      # 3️⃣ Copy the DB folder (exact overwrite)
      - name: Copy DB folder
        run: |
          rm -rf gh-pages/public/DB
          mkdir -p gh-pages/public/DB
          cp -r FrontEnd_Web/public/DB/* gh-pages/public/DB/

      # 4️⃣ Commit & Push to gh-pages
      - name: Commit and Push updates
        working-directory: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          DATE_PKT=$(TZ='Asia/Karachi' date '+%Y-%m-%d %I:%M %p PKT')
          git add .
          git commit -m "📦 Synced full DB from main (${DATE_PKT})" || echo "No changes to commit"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" gh-pages --force
